# Directory to store the statistics in [string]
statsDir = "/tmp/dtnproxy/stats/"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://node1"

# Bundle lifetime in seconds [int]
lifetime = 300


[ros]
# Format:
# [topicName, msgType, [profile]]

# Topics to subscribe to
topics = [
    [
        "/detectedImages",
        "sensor_msgs/msg/Image",
        "compress_tf",
    ],
    [
        "/status/position",
        "geometry_msgs/msg/PointStamped",
        "rate_pos",
    ],
    [
        "/status/battery",
        "sensor_msgs/msg/BatteryState",
        "rate_bat",
    ],
    [
        "/status/tempSensor",
        "diagnostic_msgs/msg/DiagnosticArray",
        "on_change",
    ],
    [
        "/temperature",
        "sensor_msgs/msg/Temperature",
        "sensor",
    ],
    [
        "/humidity",
        "sensor_msgs/msg/RelativeHumidity",
        "sensor",
    ],
]


# Services to listen to
services = [
    ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
    ]

# optimization profiles

[[profile]]
name = "compress_tf"
[[profile.module]]
name = "CombineTF"
params = ["map", "base_link"]
[[profile.module]]
name = "ImageCompress"
params = []
[[profile.module]]
name = "Compress"
params = []

[[profile]]
name = "rate_pos"
[[profile.module]]
name = "RateLimit"
params = ["10"]
[[profile.module]]
name = "Compress"
params = []

[[profile]]
name = "rate_bat"
[[profile.module]]
name = "RateLimit"
params = ["30"]
[[profile.module]]
name = "Expire"
params = []
[[profile.module]]
name = "Compress"
params = []

[[profile]]
name = "sensor"
[[profile.module]]
name = "Combine"
params = ["/temperature", "/humidity"]
[[profile.module]]
name = "Compress"
params = []
# [[profile.module]]
# name = "RateLimit"
# params = ["10"]

[[profile]]
name = "on_change"
[[profile.module]]
name = "OnChange"
params = []
[[profile.module]]
name = "Compress"
params = []
